kind = "web"
previewPath = "/"
title = "My Photos"
version = "1.0.0"
id = "artifacts/my-photos"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25253

[services.development]
run = "pnpm --filter @workspace/my-photos run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/my-photos", "run", "build" ]
publicDir = "artifacts/my-photos/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25253"
BASE_PATH = "/"
